### ISSUE TITLE
Imbue

### ISSUE THREAD

**Issue by JavEver** [Qwizer/realmap-10x#1]
O imbue não está funcionando?

**Comment by Qwizer** [comment]
qual problema esta tendo?

**Comment by JavEver** [comment]
Não sei, apenas não funciona, só abre o window, mas não da imbue nos itens.

**Comment by Qwizer** [comment]
atualizei faça um teste.

**Comment by JavEver** [comment]
Consegui da imbue no 1° nivel, mas não saiu o damage!

**Comment by JavEver** [comment]
Alguma novidade?

**Comment by Qwizer** [comment]
vou mexer nele aqui e te falo.

**Comment by Meth28** [comment]
The time doesn't go down and does not add the attributes

**Comment by tonireinbold** [comment]
Alguns da erro dizendo que você não tem os itens necessários(teste o fire damage, não vai de jeito nenhum) mesmo tendo todos os itens.
Os bônus não são aplicados.

**Comment by brunoxxt** [comment]
Eu concertei o imbue e foi muito facil

**Comment by tonireinbold** [comment]
@brunoxxt Então faça o PULL request ou explique.

**Comment by brunoxxt** [comment]
vc tem que ver o id do imbue no items.xml pegar ele e colocar no actions ... e funciona

**Comment by brunoxxt** [comment]
sei la de todos os bugs no meu servidor ja arrumei 95% deles

**Comment by JavEver** [comment]
@brunoxxt  como assim pegar id de que?

**Comment by jhonnyrs** [comment]
na verdade temos que alterar os atributos da lib moviments, mas ainda assim temos um bug que ao usar o imbue desabilita o atributo padrão do equip. Ex Shiny blade perde o +1 sword, se alguém quiser colo aqui meu lib que funciona, porem precisamos resolver o bug do onEquip.

**Comment by Qwizer** [comment]
@jhonnyrs posta o seu ai então esse do bug onEquipe sei como resolver alterando nas sources pra ele somar o atributo ao inves de substituir.
