### ISSUE TITLE
Qual RME edita o mapa?

### ISSUE THREAD

**Issue by brunoxxt** [Qwizer/realmap-10x#2]
Por favor me fala qual Rme consegue edita o mapa desse ot tou tentando tirar todos os bugs dele e ate agora nao consegui abrir o mapa vlw!!!!!!!!!!!!!

**Comment by JavEver** [comment]
@brunoxxt  posso te passar se me ajudar com o imbue!

**Comment by Qwizer** [comment]
vou postar no readme.
