### ISSUE TITLE
BUG - critical hit (fixando em contribuição)

### ISSUE THREAD

**Issue by granoob** [Qwizer/realmap-10x#5]
@Qwizer  mano sou o cara que você chamou de noob caso essa informação for irrelevante pode deletar esse issue ou falar eu eu deleto OK

mais vamos la, andei olhando em sua source e ja me deparei com esse problema os items com critical damage em ataque normal não causa critico, apenas quando se usa skill

na parte da source que esta esse problema esta no COMBAT.CPP

neste parte para ser mais exata procure por:
void Combat::CombatHealthFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)

nesta parte esta faltando a verificação veja abaixo:

	if ((damage.primary.value < 0 || damage.secondary.value < 0) && caster) {
		Player* targetPlayer = target->getPlayer();
		if (targetPlayer && caster->getPlayer() && targetPlayer->getSkull() != SKULL_BLACK) {
			damage.primary.value /= 2;
			damage.secondary.value /= 2;
		}
	}
if (g_game.combatChangeHealth(caster, target, damage)) {
		CombatConditionFunc(caster, target, params, &damage);
		CombatDispelFunc(caster, target, params, nullptr);
	}
}

mais tudo bem isso e bem fácil de resolve, basta adicionar essa verificação no caso abaixo vou colocar já a correção e basta você testar

na mesma parte do:

void Combat::CombatHealthFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)

logo baixo vamos colocar dessa forma:

void Combat::CombatHealthFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)
{
	assert(data);
	CombatDamage damage = *data;
	if (g_game.combatBlockHit(damage, caster, target, params.blockedByShield, params.blockedByArmor, params.itemId != 0)) {
		return;
	}

	if ((damage.primary.value < 0 || damage.secondary.value < 0) && caster) {
		Player* targetPlayer = target->getPlayer();
		if (targetPlayer && caster->getPlayer() && targetPlayer->getSkull() != SKULL_BLACK) {
			damage.primary.value /= 2;
			damage.secondary.value /= 2;
		}
	}
		if (caster) {
			Player* casterPlayer = caster->getPlayer();
				if (casterPlayer) {
					casterPlayer->doCriticalDamage(damage);
			}
		}
		
	if (g_game.combatChangeHealth(caster, target, damage)) {
		CombatConditionFunc(caster, target, params, &damage);
		CombatDispelFunc(caster, target, params, nullptr);
	}
}

pronto estará fixado o critical damage, faça o teste, mais caso essa informação seja algo inutil avise-me ou pode deletar esse issue

**Comment by Qwizer** [comment]
vou fazer o teste aqui, estou a procura de contribuinte pro projeto se interessar.

**Comment by granoob** [comment]
@Qwizer

obrigado, mais pode fixar isso em sua source sim, que irar funcionar
